/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DaoManager;
import dao.DaoResult;
import enums.EnumTryb;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import model.Ksiazka;
import model.Uzytkownik;
import model.Wypozyczenie;

/**
 *
 * @author Marek
 */
public class ListaMalaView extends javax.swing.JFrame {

    /**
     * Creates new form ListaOsobView
     */
    public ListaMalaView() {
    init();
    }
    
    void init(){
    
    initComponents();
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
    }
    
    
     JTable jTable1;

    ListaMalaView(EnumTryb enumTryb, Ksiazka ksiazka) {
        init();
        jButton2.setVisible(false);
        TableModel tm;
        TableColumnModel tcm=new DefaultTableColumnModel();
        String headers[] = { "Id","Czytelnik, data wypożyczenia" };
        String data[][]=new String[ksiazka.getWypozyczenie().size()][2];
        
        int i=0;
        for(Wypozyczenie u: ksiazka.getWypozyczenie()){
        
            data[i][0]=String.valueOf(u.getId());
            data[i][1]=u.getUzytkownik().getImieNazwisko()+ " "+u.getData().toString();
             i++; 
                    }
        
        jTable1=new JTable(data, headers);
        JScrollPane jScrollPane1=new  JScrollPane(jTable1);
        jScrollPane1.setSize(600,500);
        jTable1.getColumnModel().removeColumn(jTable1.getColumnModel().getColumn(0));
        jPanel1.add(jScrollPane1, BorderLayout.CENTER);
        
        
    }

    public ListaMalaView(EnumTryb enumTryb) {
        
        
   init();
        jButton1.setVisible(false);
        DaoManager dm=new DaoManager();
        
        DaoResult res=dm.getRecomendations(session.Session.user.getId());
        if(res.isIsError()){
        JOptionPane.showMessageDialog(null, res.getMessString());
        this.setVisible(false);
        }
        
        List<Ksiazka> ksiazki=(List<Ksiazka>) res.getObject();
        TableModel tm;
        TableColumnModel tcm=new DefaultTableColumnModel();
        String headers[] = { "Id","Książka" };
        String data[][]=new String[ksiazki.size()][2];
        
        int i=0;
        for(Ksiazka u: ksiazki){
        
            data[i][0]=String.valueOf(u.getId());
            data[i][1]=u.getAutor()+ " - "+u.getTytul();
             i++; 
                    }
        
        jTable1=new JTable(data, headers);
        JScrollPane jScrollPane1=new  JScrollPane(jTable1);
        jScrollPane1.setSize(600,500);
        jTable1.getColumnModel().removeColumn(jTable1.getColumnModel().getColumn(0));
        jPanel1.add(jScrollPane1, BorderLayout.CENTER);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jButton1.setText("ZWRÓC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("POKAŻ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(594, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        DaoManager dm=new DaoManager();
        DaoResult dr=dm.returnBook(Integer.parseInt(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString()));
        JOptionPane.showMessageDialog(null, dr.getMessString());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        KsiazkaView kv=new KsiazkaView(EnumTryb.POKAZ_KSIAZKE,Integer.parseInt(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString()) );
        kv.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaMalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaMalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaMalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaMalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaMalaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
